import {
  // @ts-expect-error - This type is used in other files
  type Icon as LucideIcon,
  Loader2,
  Github,
  Code,
  Mail,
  MailOpen,
  Moon,
  SunMedium,
  Twitter,
  User,
  X,
  Menu,
  Home,
  Folder,
  MessageSquare,
  Briefcase,
  Settings,
  LogOut,
  DollarSign,
  Users,
  Trophy,
  Code2,
  Eye,
  FileText,
  Award,
  Link,
  Check,
  Image,
  Chrome as Google,
  Plus,
  Layers,
  Linkedin,
  Inbox,
  AlertCircle,
  Search,
  RotateCcw,
  Calendar,
  Filter,
  ChevronDown,
  ArrowLeft,
  CheckCircle,
  CheckSquare,
  XCircle,
  Clock,
  Pencil,
  Send,
  Star,
  Sparkles,
  ArrowRight,
  ClipboardList,
  Activity,
  BarChart,
  Undo,
  TrendingUp,
  Layout,
} from 'lucide-react';

// @ts-expect-error - This type is used in other files
export type Icon = LucideIcon;

export const Icons = {
  logo: Code2,
  spinner: Loader2,
  gitHub: Github,
  code: Code,
  mail: Mail,
  mailOpen: MailOpen,
  moon: Moon,
  sun: SunMedium,
  twitter: Twitter,
  user: User,
  x: X,
  menu: Menu,
  home: Home,
  folder: Folder,
  message: MessageSquare,
  briefcase: Briefcase,
  settings: Settings,
  logout: LogOut,
  dollarSign: DollarSign,
  users: Users,
  trophy: Trophy,
  eye: Eye,
  fileText: FileText,
  award: Award,
  link: Link,
  check: Check,
  image: Image,
  google: Google,
  plus: Plus,
  layers: Layers,
  linkedin: Linkedin,
  inbox: Inbox,
  alertCircle: AlertCircle,
  search: Search,
  reset: RotateCcw,
  calendar: Calendar,
  filter: Filter,
  chevronDown: ChevronDown,
  arrowLeft: ArrowLeft,
  checkCircle: CheckCircle,
  checkSquare: CheckSquare,
  xCircle: XCircle,
  clock: Clock,
  edit: Pencil,
  send: Send,
  star: Star,
  sparkles: Sparkles,
  arrowRight: ArrowRight,
  clipboardList: ClipboardList,
  activity: Activity,
  messageSquare: MessageSquare,
  barChart: BarChart,
  undo: Undo,
  trendingUp: TrendingUp,
  layout: Layout,
} as const;
